[package]
name = "is_stuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is-docker = "0.2.0"
is-interactive = "0.1.0"
is-wsl = "0.4.0"

[lib]
crate-type = ["cdylib"]
